const char * _sound_service = 
"<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\" \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"
"<node name=\"/com/canonical/indicators/sound\">\n"
"  <interface name=\"com.canonical.indicators.sound\">\n"
"    <method name = \"GetSinkMute\">\n"
"        <annotation name=\"org.freedesktop.DBus.GLib.CSymbol\" value=\"sound_service_dbus_get_sink_mute\"/>\n"
"        <arg type='b' name='mute_input' direction=\"out\"/>\n"
"    </method>\n"
"\n"
"    <method name = \"GetSinkAvailability\">\n"
"        <annotation name=\"org.freedesktop.DBus.GLib.CSymbol\" value=\"sound_service_dbus_get_sink_availability\"/>\n"
"        <arg type='b' name='availability_input' direction=\"out\"/>\n"
"    </method>\n"
"\n"
"<!-- Will need to hook up another signal which monitors for volume change \n"
"Our respective UI element should listen to this and therefore will be updated with accurate setting-->\n"
"<!-- Triggered when a sink is muted but the input has been sent to that sink -->\n"
"    <signal name=\"SinkInputWhileMuted\">\n"
"      <arg name=\"block_value\" type=\"b\" direction=\"out\"/>\n"
"    </signal>\n"
"    \n"
"    <signal name=\"SinkMuteUpdate\">\n"
"      <arg name=\"mute_value\" type=\"b\" direction=\"out\"/>\n"
"    </signal>\n"
"\n"
"    <signal name=\"SinkAvailableUpdate\">\n"
"      <arg name=\"available_value\" type=\"b\" direction=\"out\"/>\n"
"    </signal>\n"
"\n"
"  </interface>\n"
"</node>\n"
"\n"
;
